title: Aaron Farmer # your name (or website title) here
logo: "/images/avatar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduated UNCC in December 2022 with a BS in CS. Year Up Student.
  <br><br>
  <a href="https://www.linkedin.com/in/aaron-j-farmer/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
